apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kubernetes
  namespace: prometheus
spec:
  groups:
  - name: kubernetes
    rules:
    - alert: KubeVersionMismatch
      expr: |
        count(count by (gitVersion) (label_replace(kubernetes_build_info{job!~"kube-dns|coredns"},"gitVersion","$1","gitVersion","(v[0-9]*.[0-9]*).*"))) > 1
      for: 15m
      labels:
        severity: warning
      annotations:
        summary: Different semantic versions of Kubernetes components running
