apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: pods
  namespace: prometheus
spec:
  groups:
  - name: pods
    rules:
    - alert: NoPodMetrics
      expr: absent(kube_pod_container_status_restarts_total) > 0
      for: 5m
      labels:
        severity: error
      annotations:
        summary: No pod metrics

    - alert: PodRestartedMoreThanFiveOver10m
      expr: |
        increase(kube_pod_container_status_restarts_total[10m]) > 5
      for: 1m
      labels:
        severity: error
      annotations:
        summary: Pod {{ $labels.pod }} restarted more than five times in 10 mins

    - alert: PodNotReady5m
      expr: |
        count(kube_pod_info{created_by_kind!="Job"} and on(pod, namespace) kube_pod_status_ready{condition="false"} == 1) by (pod) > 0 
      for: 5m
      labels:
        severity: error
      annotations:
        summary: Pod {{ $labels.namespace }}/{{ $labels.pod }} not ready for 5 mins

    - alert: PodBadPhase5m
      expr: |
       kube_pod_status_phase{phase!~"(Running|Succeeded)"} > 0
      for: 5m
      labels:
        severity: error
      annotations:
        summary: Pod {{ $labels.namespace }}/{{ $labels.pod }} is phase={{ $labels.phase }} for 5 mins
  
    - alert: PodWaiting5m
      expr: |
        kube_pod_container_status_waiting_reason > 0
      for: 5m
      labels:
        severity: error
      annotations:
        summary: Pod {{ $labels.namespace }}/{{ $labels.pod }} waiting for 5 mins on {{ $labels.reason }}

    - alert: PodOOMkilledTwoTimes10m
      expr: |
        kube_pod_container_status_last_terminated_reason{reason="OOMKilled"} == 1 
        and on(container)
        increase(kube_pod_container_status_restarts_total[10m]) > 2
      labels:
        severity: error
      annotations:
        summary: Pod {{ $labels.pod }} exited with '{{ $labels.reason }}'

    - alert: PodOOMkilledFiveTimes10m
      expr: |
        kube_pod_container_status_last_terminated_reason{reason!="Completed"} == 1 
        and on(container)
        increase(kube_pod_container_status_restarts_total[10m]) > 5
      labels:
        severity: error
      annotations:
        summary: Pod {{ $labels.pod }} exited with '{{ $labels.reason }}'

    - alert: PodEvicted
      expr: |
        kube_pod_container_status_last_terminated_reason{reason="Evicted"} == 1 
        and on(container)
        increase(kube_pod_container_status_restarts_total[10m]) > 0
      labels:
        severity: error
      annotations:
        summary: Pod {{ $labels.pod }} was evicted'
