apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: pv
  namespace: prometheus
spec:
  groups:
  - name: pv
    rules:
    - alert: NoPVMetrics
      expr: absent(kubelet_volume_stats_used_bytes) > 0
      for: 5m
      labels:
        severity: error
      annotations:
        summary: No PV usage metrics

    - alert: WarningPVUsage
      expr: |
        100 * kubelet_volume_stats_used_bytes / kubelet_volume_stats_capacity_bytes > 85
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: PVC {{ $labels.persistentvolumeclaim }} is {{ $value }}% full

    - alert: ErrorPVUsage
      expr: |
        100 * kubelet_volume_stats_used_bytes / kubelet_volume_stats_capacity_bytes > 90
      for: 5m
      labels:
        severity: error
      annotations:
        summary: PVC {{ $labels.persistentvolumeclaim }} is {{ $value }}% full

    - alert: CriticalPVUsage
      expr: |
        100 * kubelet_volume_stats_used_bytes / kubelet_volume_stats_capacity_bytes > 95
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: PVC {{ $labels.persistentvolumeclaim }} is {{ $value }}% full

    - alert: LowInodes
      expr: |
        kubelet_volume_stats_inodes_free < 50000
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: PVC {{ $labels.persistentvolumeclaim }} has {{ $value }} < 50k inodes available
  
    - alert: CriticalInodes
      expr: |
        kubelet_volume_stats_inodes_free < 5000
      for: 5m
      labels:
        severity: error
      annotations:
        summary: PVC {{ $labels.persistentvolumeclaim }} has {{ $value }} < 5k inodes available

    - alert: PVError
      expr: |
        kube_persistentvolume_status_phase{phase=~"Failed|Pending"} > 0
      for: 5m
      labels:
        severity: error
      annotations:
        summary: PVC {{ $labels.persistentvolumeclaim }} is {{ $labels.phase }}
