name: 'Run Kubeval'

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  kubeval:
    name: kubeval
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: azure/k8s-lint@v1
      with:
        manifests: |
          rules/*.yaml
